/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Scanner;
import java.util.UUID;
import java.util.ArrayList;
import org.example.entities.User;
import org.example.util.userServiceutil;
import org.example.services.UserBookingService;

public class App {

    public static void main(String[] args) {
        System.out.println("running the IRCTC application");
        Scanner scanner = new Scanner(System.in);
        int option = 0;
        UserBookingService userBookingService;
        try
        {
            userBookingService = new UserBookingService();
        }
        catch(Exception e)
        {
            System.out.println("Error loading user data: " + e.getMessage());
            scanner.close();
            return;
        }
        while(option!=6)
        {
            System.out.println("1. Login");
            System.out.println("2. Sign Up");
            System.out.println("3. Fetch Booking");
            System.out.println("4. Cancel Booking");
            System.out.println("5. Find Train");
            System.out.println("6. Book Ticket");
            System.out.println("7. Exit");
            System.out.print("Enter your option: ");
            option = scanner.nextInt();
            switch(option)
            {
                case 1:
                    // Handle login
                    System.out.print("Enter username to login: ");
                    String loginUsername = scanner.next();
                    System.out.print("Enter password to sign up: ");
                    String loginPassword = scanner.next();
                    User loginUser = new User(loginUsername, loginPassword, userServiceutil.hashPassword(loginPassword), new ArrayList<>(), UUID.randomUUID().toString());
                    try
                    {
                        userBookingService = new UserBookingService(loginUser);
                    }
                    catch(Exception e)
                    {
                        System.out.println("Error loading user data: " + e.getMessage());
                        return;
                    }
                    Boolean loginSuccess = userBookingService.loginUser();
                    if(loginSuccess)
                    {
                        System.out.println("Login successful!");

                    }
                    else
                    {
                        System.out.println("Login failed. Please check your credentials.");
                    }
                    break;
                case 2:
                    // Handle sign up
                    System.out.print("Enter username: ");
                    String username = scanner.next();
                    System.out.print("Enter password: ");
                    String password = scanner.next();
                    User signUpUser = new User(username, password, userServiceutil.hashPassword(password),new ArrayList<>(), UUID.randomUUID().toString());  
                     
                    Boolean signUpSuccess = userBookingService.signUp(signUpUser);
                    if(signUpSuccess)
                    {
                        System.out.println("Sign up successful!");
                    }
                    else
                    {
                        System.out.println("Sign up failed. Please try again.");
                    }
                    break;
                case 3:
                    // Handle fetch booking
                    userBookingService.fetchBooking();
                    break;
                case 4:
                    // Handle cancel booking
                    System.out.print("Enter ticket ID to cancel: ");
                    String ticketId = scanner.next();
                    Boolean cancelSuccess = userBookingService.cancelBooking(ticketId);
                    if(cancelSuccess)
                    {
                        System.out.println("Booking cancelled successfully!");
                    }
                    else
                    {
                        System.out.println("Cancellation failed. Please check the ticket ID.");
                    }
                    break;
                case 5:
                    // Find train 
                    System.out.print("Enter source station: ");
                    String source = scanner.next();
                    System.out.print("Enter destination station: ");
                    String destination = scanner.next();
                    userBookingService.findTrain(source, destination);
                    break;
                case 6:
                    // Book ticket
                    System.out.print("Enter train ID to book: ");
                    String trainId = scanner.next();
                    System.out.print("Enter source station: ");
                    String bookSource = scanner.next();
                    System.out.print("Enter destination station: ");
                    String bookDestination = scanner.next();
                    userBookingService.bookTicket(trainId, bookSource, bookDestination);
                    break;                    
                case 7:
                    System.out.println("Exiting the application.");
                    break;
                default:
                    System.out.println("Invalid option. Please try again.");
            }
        }
        scanner.close();
    }
}
