/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.net.InetSocketAddress;
import org.example.handler.TaskHandler;
import org.example.handler.UserHandler;
public class HttpServerApp {


    public static void main(String[] args) throws IOException {
        
        HttpServer server = HttpServer.create(new InetSocketAddress(8080), 0);
        server.createContext("/task", TaskHandler::handle);
        server.createContext("/user", UserHandler::handle);
        server.start();
        System.out.println("Server started on port 8080");
        
    }

}
